global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app1'
    static_configs:
      - targets: ['app1:8080']
    metrics_path: /actuator/prometheus

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
    metrics_path: /metrics