version: '3.8'
services:
  app1:
    build: .
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/sql_db
      SPRING_DATASOURCE_USERNAME: Mahmoud
      SPRING_DATASOURCE_PASSWORD: Mahmoud12
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8084:8080"

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mody1121
      MYSQL_DATABASE: sql_db
      MYSQL_USER: Mahmoud
      MYSQL_PASSWORD: Mahmoud12
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

  app2:
    build: .
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/pg_db
      SPRING_DATASOURCE_USERNAME: pguser
      SPRING_DATASOURCE_PASSWORD: pgpass
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8085:8080"

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_DB: pg_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data

volumes:
  mysql-volume:
  pg-volume:
