apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  namespace: prod
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring-app
          image: spring-pet-clinic:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
