apiVersion: v1
kind: Service
metadata:
  name: spring-nodeport
  namespace: prod
  labels:
    app: spring-app
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
